# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(708, 582)
        self.imie = QtWidgets.QLabel(parent=Dialog)
        self.imie.setGeometry(QtCore.QRect(23, 40, 53, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.imie.setFont(font)
        self.imie.setAutoFillBackground(False)
        self.imie.setObjectName("imie")
        self.nazwisko = QtWidgets.QLabel(parent=Dialog)
        self.nazwisko.setGeometry(QtCore.QRect(21, 77, 110, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nazwisko.setFont(font)
        self.nazwisko.setAutoFillBackground(False)
        self.nazwisko.setObjectName("nazwisko")
        self.radioButton = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton.setGeometry(QtCore.QRect(28, 120, 113, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setAutoFillBackground(False)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(28, 155, 101, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(28, 190, 132, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.checkBox = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox.setGeometry(QtCore.QRect(60, 240, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.Reserv = QtWidgets.QPushButton(parent=Dialog)
        self.Reserv.setGeometry(QtCore.QRect(530, 280, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Reserv.setFont(font)
        self.Reserv.setObjectName("Reserv")
        self.label_text = QtWidgets.QLabel(parent=Dialog)
        self.label_text.setGeometry(QtCore.QRect(10, 370, 681, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_text.setFont(font)
        self.label_text.setText("")
        self.label_text.setObjectName("label_text")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(150, 40, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setTabletTracking(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 80, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.imie.setText(_translate("Dialog", "Imie"))
        self.nazwisko.setText(_translate("Dialog", "Nazwisko"))
        self.radioButton.setText(_translate("Dialog", "Internista"))
        self.radioButton_2.setText(_translate("Dialog", "Pediatra"))
        self.radioButton_3.setText(_translate("Dialog", "Dermatolog"))
        self.checkBox.setText(_translate("Dialog", "Wizyta prywatna"))
        self.Reserv.setText(_translate("Dialog", "Rezerwuj"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
